### ISSUE TITLE
NoSuchMethodError: org.apache.bcel.generic.ObjectType.getInstance

### ISSUE THREAD

**Issue by jbdundas** [spotbugs/sonar-findbugs#176]
We are getting this error while running analysis on Sonarqube 5.6.5  with Findbugs plugin:-

```
09:49:29.707 ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Can not execute Findbugs
        at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:169)
        at org.sonar.plugins.findbugs.FindbugsSensor.execute(FindbugsSensor.java:96)
        at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
        at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.bcel.generic.ObjectType.getInstance(Ljava/lang/String;)Lorg/apache/bcel/generic/ObjectType;
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:163)
        ... 31 more
Caused by: java.lang.NoSuchMethodError: org.apache.bcel.generic.ObjectType.getInstance(Ljava/lang/String;)Lorg/apache/bcel/generic/ObjectType;
        at edu.umd.cs.findbugs.ba.ObjectTypeFactory.getInstance(ObjectTypeFactory.java:69)
        at edu.umd.cs.findbugs.ba.ObjectTypeFactory.getInstance(ObjectTypeFactory.java:49)
        at edu.umd.cs.findbugs.ba.ch.Subtypes2.<clinit>(Subtypes2.java:134)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at edu.umd.cs.findbugs.classfile.ReflectionDatabaseFactory.createUsingConstructor(ReflectionDatabaseFactory.java:113)
        at edu.umd.cs.findbugs.classfile.ReflectionDatabaseFactory.createDatabase(ReflectionDatabaseFactory.java:59)
        at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getDatabase(AnalysisCache.java:489)
        at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getDatabase(AnalysisCache.java:468)
        at edu.umd.cs.findbugs.ba.AnalysisContext.getSubtypes2(AnalysisContext.java:1018)
        at edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:974)
        at edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:877)
        at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
        at org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:216)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by jbdundas** [comment]
3.4.4  is the plugin installed and this analysis is being run via Sonar Jenkins plugin.

**Comment by h3xstream** [comment]
@jbdundas Please update the description of your issue to use the template.
