### ISSUE TITLE
 SonarQube › java.lang.IllegalArgumentException: Unable to register token in file

### ISSUE THREAD

**Issue by gvasquez95** [spotbugs/sonar-findbugs#181]
## Issue Description

It reports:

`Caused by: java.lang.IllegalArgumentException: 103 is not a valid line offset for pointer. File WebContent/chilexpress/reportes2.jsp has 102 character(s) at line 1 `

I see nothing strange in the first line of the file, as it only has the DOCTYPE reference for the HTML code, as follows:

`<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">`

## Stacktrace
```
[WARNING] 13:14:24.015 Giving up highlighting/handling duplication for file WebContent/chilexpress/reportes2.jsp
java.lang.IllegalArgumentException: Unable to register token in file WebContent/chilexpress/reportes2.jsp
	at org.sonar.api.batch.sensor.cpd.internal.DefaultCpdTokens.addToken(DefaultCpdTokens.java:79)
	at org.sonar.plugins.findbugs.language.JspTokensVisitor.highlightAndDuplicate(JspTokensVisitor.java:67)
	at org.sonar.plugins.findbugs.language.JspTokensVisitor.startDocument(JspTokensVisitor.java:49)
	at org.sonar.plugins.findbugs.language.visitor.HtmlAstScanner.scan(HtmlAstScanner.java:74)
	at org.sonar.plugins.findbugs.language.visitor.HtmlAstScanner.scan(HtmlAstScanner.java:58)
	at org.sonar.plugins.findbugs.language.JspSyntaxSensor.execute(JspSyntaxSensor.java:66)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy26.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:77)
	at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:139)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:955)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.IllegalArgumentException: 103 is not a valid line offset for pointer. File WebContent/chilexpress/reportes2.jsp has 102 character(s) at line 1
	at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:312)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:246)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:262)
	at org.sonar.api.batch.sensor.cpd.internal.DefaultCpdTokens.addToken(DefaultCpdTokens.java:77)
	... 58 common frames omitted
```

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | Version 6.7 (build 33306)   |
| Sonar-FindBugs     | 3.6.0   |
| Maven              | 3.5.2   |
| Java               | openjdk-1.8.0.161-0.b14.36.amzn1.x86_64   |
|sonar-maven-plugin | 3.3.0.603 | 

## Code

See attached "offending" file
[reportes2.jsp.zip](https://github.com/spotbugs/sonar-findbugs/files/1852144/reportes2.jsp.zip)

**Comment by h3xstream** [comment]
TODO: Double check if [sonar-web](https://github.com/SonarSource/sonar-web) is also crash when parsing the jsp file...

**Comment by h3xstream** [comment]
It could be the first 3 bytes that are causing problem.
```
$ cat reportes2.jsp | xxd | head
00000000: efbb bf3c 2144 4f43 5459 5045 2068 746d  ...<!DOCTYPE htm
00000010: 6c20 5055 424c 4943 2022 2d2f 2f57 3343  l PUBLIC "-//W3C
00000020: 2f2f 4454 4420 4854 4d4c 2034 2e30 3120  //DTD HTML 4.01
00000030: 5472 616e 7369 7469 6f6e 616c 2f2f 454e  Transitional//EN
00000040: 2220 2268 7474 703a 2f2f 7777 772e 7733  " "http://www.w3
00000050: 2e6f 7267 2f54 522f 6874 6d6c 342f 6c6f  .org/TR/html4/lo
00000060: 6f73 652e 6474 6422 3e0a 3c68 746d 6c3e  ose.dtd">.<html>
00000070: 0a3c 6865 6164 3e0a 3c6d 6574 6120 6368  .<head>.<meta ch
00000080: 6172 7365 743d 2275 7466 2d38 223e 0a3c  arset="utf-8">.<
00000090: 6d65 7461 2068 7474 702d 6571 7569 763d  meta http-equiv=
```

**Comment by gvasquez-waypoint** [comment]
@h3xstream will try cleaning the head and re processing the file

**Comment by h3xstream** [comment]
@gvasquez-waypoint Yup it would make a good test to change this specific file.
[Byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark) should be handled.

**Comment by CCFenner** [comment]
I fixed this issue by recreating the file and copy&paste the coding.

**Comment by gtoison** [comment]
This issue is obsolete now that SonarQube has built-in support for JSP: the plugin no longer has to handle the JSP syntax and the corresponding code has been deleted.
Please feel free to reopen if that's still an issue
