### ISSUE TITLE
Analysis fails on Java 10

### ISSUE THREAD

**Issue by baaym** [spotbugs/sonar-findbugs#184]
## Issue Description

Hi all,

Analysis fails when running on Java 10. Since a Java 10 compatible update of sonar-java was released yesterday, I was hoping to get an analysis going. Unfortunately it seems that the sonar-findbugs plugin doesn't support this yet.

Looking at the error below I'm guessing the `asm` dependency needs updating, since it already supports the new bytecode format. I however have no clue what impact this is going to have ;)

```
[INFO] --- sonar-maven-plugin:3.4.0.905:sonar (default-cli) @ xxx ---
[INFO] User cache: /root/.sonar/cache
[INFO] SonarQube version: 7.0.0
[INFO] Default locale: "en", source code encoding: "UTF-8"
[INFO] Publish mode
[INFO] Load global settings
[INFO] Load global settings (done) | time=206ms
[INFO] Server id: xxx
[INFO] User cache: /root/.sonar/cache
[INFO] Load plugins index
[INFO] Load plugins index (done) | time=93ms
[INFO] Load/download plugins
[INFO] Load/download plugins (done) | time=1752ms
[INFO] Process project properties
[INFO] Load project repositories
[INFO] Load project repositories (done) | time=617ms
[INFO] Execute project builders
[INFO] Execute project builders (done) | time=1ms
[INFO] Load quality profiles
[INFO] Load quality profiles (done) | time=155ms
[INFO] Load active rules
[INFO] Load active rules (done) | time=1536ms
[INFO] Load metrics repository
[INFO] Load metrics repository (done) | time=94ms
[INFO] Project key: xxx:xxx
[INFO] Branch key: develop
[INFO] -------------  Scan XXX
[INFO] Base dir: /builds/xxx
[INFO] Working dir: /builds/xxx
[INFO] Source paths: pom.xml, src/main/java
[INFO] Test paths: src/test/java
[INFO] Source encoding: UTF-8, default locale: en
[INFO] Load server rules
[INFO] Load server rules (done) | time=168ms
[INFO] Index files
[INFO] 41 files indexed
[INFO] Quality profile for java: XXX
[INFO] Sensor JavaSquidSensor [java]
[INFO] Configured Java source version (sonar.java.source): 5
[INFO] JavaClasspath initialization
[INFO] JavaClasspath initialization (done) | time=23ms
[INFO] JavaTestClasspath initialization
[INFO] JavaTestClasspath initialization (done) | time=3ms
[INFO] Java Main Files AST scan
[INFO] 31 source files to be analyzed
[WARNING] Classes not found during the analysis : [java.sql.Connection, java.sql.SQLException]
[INFO] Java Main Files AST scan (done) | time=4317ms
[INFO] Java Test Files AST scan
[INFO] 9 source files to be analyzed
[INFO] 31/31 source files have been analyzed
[INFO] 9/9 source files have been analyzed
[INFO] Java Test Files AST scan (done) | time=403ms
[INFO] Sensor JavaSquidSensor [java] (done) | time=5845ms
[INFO] Sensor FindBugs Sensor [findbugs]
[INFO] Loading findbugs plugin: /builds/xxx/target/sonar/findbugs/fb-contrib.jar
[INFO] Loading findbugs plugin: /builds/xxx/target/sonar/findbugs/findsecbugs-plugin.jar
[INFO] Findbugs output report: /builds/xxx/target/sonar/findbugs-result.xml
The following errors occurred during analysis:
  Error scanning xxx.Foo for referenced classes
    java.lang.IllegalArgumentException
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
      At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
      At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
      At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
      At edu.umd.cs.findbugs.FindBugs2.buildReferencedClassSet(FindBugs2.java:773)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:219)
      At org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)
      At java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
      At java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
      At java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      At java.base/java.lang.Thread.run(Thread.java:844)
  Unable to get XClass for java/lang/Integer
    java.lang.IllegalArgumentException
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
      At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
      At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
      At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
      At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:687)
      At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:970)
      At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:876)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:222)
      At org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)
      At java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
      At java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
      At java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      At java.base/java.lang.Thread.run(Thread.java:844)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:26 min
[INFO] Finished at: 2018-04-17T06:18:48Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar (default-cli) on project xxx: Can not execute Findbugs: java.lang.RuntimeException: edu.umd.cs.findbugs.NoClassesFoundToAnalyzeException: No classes found to analyze in /builds/xxx/target/classes/xxx/Foo.class
```

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.0.0|
| Sonar-FindBugs     | 3.7.0 |
| Maven              | 3.5.3 |
| Gradle             | N/A |
| Java               | 10   |

## Code (If needed)

Any project will do

**Comment by marx-freedom** [comment]
https://github.com/spotbugs/spotbugs/issues/593

We are also waiting for new spotbugs version and sonar plugin update...

**Comment by stil4m** [comment]
When will 3.8 be released? It seems that spotbugs is already updated, which should resolve this issue. It currently blocks usage of Java 10 in Sonar in combination with the Sonar FindBugs plugin.

**Comment by alexVengrovsk** [comment]
Please, speed-up fixing of this issue

**Comment by michaelajr** [comment]
Hey there. Is this on anyone's radar?

**Comment by mykolap** [comment]
checked with snapshot 3.8, everything works
Please, release 3.8

**Comment by h3xstream** [comment]
I will some tests later but it should be integrated for the next release. #192

**Comment by mwreczycki** [comment]
Any update on release of 3.8 ?

**Comment by baaym** [comment]
@h3xstream: is this still on the radar? We're approaching the next LTS release of Java, which will make more developers jump to a modular Java environment. It would be nice if this fix would already be released.

**Comment by pgodithi** [comment]
Hey I am using oracle java 10 and using sonar for code analysis, getting the following error, can anyone tell me the solution for this.
sonarqube version: 6.7.3
find bugs plugin: 3.7.0

at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:275)
at org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)

Caused by: java.lang.IllegalStateException: Can not execute Findbugs

**Comment by kuhnroyal** [comment]
@h3xstream 3.8 seems to be released but there is no tag and no update available. Can you comment on the current status?

**Comment by PyvesB** [comment]
Apparently there is some ongoing release work in #199. In the meantime I've simply rebuilt the plugin from source (simply run `mvn clean package` in the root of the project) and uploaded the resulting _.jar_ to my SonarQube server. Java 10 projects are being analysed like a charm. 😉

**Comment by BenedictRasmussen** [comment]
It appears #199 was resolved and the new version should hit the marketplace soon. As of seven days ago, @VinodAnandan said he would be performing the release to the sonar marketplace. I have not seen it yet, but hopefully soon.

**Comment by Thunderforge** [comment]
It looks to me like sonar-findbugs 3.8.0 has been deployed to the MarketPlace. Can this issue be closed now?

**Comment by BenedictRasmussen** [comment]
I can confirm that upgrading to SonarQube 7.3 and sonar-findbugs 3.8.0 allows me to scan Java 10 projects.

**Comment by VinodAnandan** [comment]
@BenedictRasmussen Thanks for the confirmation :)
