### ISSUE TITLE
Startup issues with sonarqube 7.3

### ISSUE THREAD

**Issue by pethers** [spotbugs/sonar-findbugs#204]
## Issue Description

Failed to startup sonarqube 7.3, tested different version all get below exception.

ava.lang.IllegalStateException: Fail to load plugin Findbugs [findbugs]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:586)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/BatchExtension
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	at org.sonar.plugins.findbugs.FindbugsPlugin.define(FindbugsPlugin.java:55)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:72)
	... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.BatchExtension
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 24 common frames omitted

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.3   |
| Sonar-FindBugs     | 3.7/3.9.0-SNAPSHOT   |
| Java               | 1.8  |

**Comment by pethers** [comment]
Caused by https://jira.sonarsource.com/browse/SONAR-10138 in 7.3.

**Comment by agabrys** [comment]
Unfortunately, PR #208 has fixed only server side startup, but executing analysis is broken:

> [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.1.1168:sonar (default-cli) on project lesscss-maven-plugin: org.sonar.plugins.findbugs.FindbugsSensor has unsatisfied dependency 'class org.sonar.plugins.findbugs.resource.ByteCodeResourceLocator' for constructor 'public org.sonar.plugins.findbugs.FindbugsSensor(org.sonar.api.profiles.RulesProfile,org.sonar.api.batch.rule.ActiveRules,org.sonar.api.batch.sensor.SensorContext,org.sonar.plugins.findbugs.FindbugsExecutor,org.sonar.plugins.java.api.JavaResourceLocator,org.sonar.api.batch.fs.FileSystem,org.sonar.plugins.findbugs.resource.ByteCodeResourceLocator)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@7250fc3d:166<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@6983a6b3:224<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@196840a9:9<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@d209f52:42<| -> [Help 1]

**Comment by h3xstream** [comment]
This should all be fix now : 

https://github.com/spotbugs/sonar-findbugs/pull/208
https://github.com/spotbugs/sonar-findbugs/pull/209

**Comment by agabrys** [comment]
I confirm that the latest `master` (d3363ac9e0ace7a6c83e0fb83c7c9ea6b2e844cd) works correctly.
