### ISSUE TITLE
SonarQube fails to load a plugin compiled with SBT

### ISSUE THREAD

**Issue by MaxiLagos54** [spotbugs/sonar-findbugs#230]
## Issue Description

I'm working in a new plugin. It is written in Scala and compiled with SBT. I'm getting the next error when trying to load the jar in SonarQube

> java.lang.IllegalStateException: Fail to load plugin Scala-Test [scalatest]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:586)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unable to register extension com.clarotest.sonar.scala.Scala from plugin 'scalatest'
	at org.sonar.core.platform.ComponentContainer.addExtension(ComponentContainer.java:242)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtension(ServerExtensionInstaller.java:119)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:74)
	... 9 common frames omitted
Caused by: java.lang.NoClassDefFoundError: scalariform/ScalaVersion
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.picocontainer.injectors.AdaptingInjection$1.run(AdaptingInjection.java:203)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.picocontainer.injectors.AdaptingInjection.injectionMethodAnnotated(AdaptingInjection.java:200)
	at org.picocontainer.injectors.AdaptingInjection.methodAnnotatedInjectionAdapter(AdaptingInjection.java:171)
	at org.picocontainer.injectors.AdaptingInjection.createComponentAdapter(AdaptingInjection.java:70)
	at org.picocontainer.behaviors.AbstractBehaviorFactory.createComponentAdapter(AbstractBehaviorFactory.java:44)
	at org.picocontainer.behaviors.OptInCaching.createComponentAdapter(OptInCaching.java:45)
	at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:536)
	at org.picocontainer.DefaultPicoContainer.access$300(DefaultPicoContainer.java:84)
	at org.picocontainer.DefaultPicoContainer$AsPropertiesPicoContainer.addComponent(DefaultPicoContainer.java:1149)
	at org.sonar.core.platform.ComponentContainer.addExtension(ComponentContainer.java:240)
	... 11 common frames omitted
Caused by: java.lang.ClassNotFoundException: scalariform.ScalaVersion
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 25 common frames omitted

I tried loading a similar plugin (sonar-scala) and it works fine when trying to load the jar published as release. But, it fails with the same error when I compile it at my end by using $ sbt package.

So, the question is, am I doing something wrong? Is there any other way to compile it and get it working?

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.4   |
| SBT     | 1.1.2   |
| Scala              | 2.12.7   |

## Code (If needed)

This is my build.sbt (including the attributes in the manifest):

```
name := "scala-test-plugin"

version := "0.1"

scalaVersion := "2.12.7"

scalacOptions := Seq(
  "-unchecked",
  "-deprecation",
  "-encoding",
  "utf8",
  "-feature",
  "-language:reflectiveCalls"
)

libraryDependencies ++= List(
  "org.typelevel" %% "cats-core" % "1.4.0",
  "org.scalariform" %% "scalariform" % "0.2.6",
  "org.sonarsource.sonarqube" % "sonar-plugin-api" % "7.4",
  "org.sonarsource.update-center" % "sonar-update-center-common" % "1.21.0.561",
  "org.slf4j" % "slf4j-api" % "1.7.25" % Provided
)

javacOptions := Seq("-Xlint:deprecation")
cancelable in Global := true

import sbt._
import Keys._

packageOptions in (Compile, packageBin) +=
  Package.ManifestAttributes(
    "Manifest-Version" -> "true",
    "Plugin-Description" -> "Testing",
    "Plugin-Display-Version" -> "1.0.0-SNAPSHOT",
    "Specification-Title" -> "sonar-test-scala",
    "Implementation-Vendor-Id" -> "com.clarotest.sonar",
    "Plugin-Organization" -> "Clarolab",
    "Plugin-Developers" -> "Maxi Lagos, Lea Ferrara",
    "Plugin-IssueTrackerUrl" -> "https://bitbucket.org/clarolabdev/sonar-scala-plugin-test/issues",
    "Plugin-ChildFirstClassLoader" -> "false",
    "Plugin-OrganizationUrl" -> "https://clarolab.com",
    "Plugin-Key" -> "scala-test",
    "Plugin-Class" -> "com.clarotest.sonar.scala.ScalaTestPlugin",
    "Plugin-Name" -> "Scala-Test",
    "Implementation-Title" -> "sonar-test-scala",
    "Plugin-SourcesUrl" -> "com.clarotest.sonar",
    "Implementation-Version" -> "1.0.0-SNAPSHOT",
    "SonarLint-Supported" -> "false",
    "Specification-Vendor" -> "com.clarotest.sonar",
    "Plugin-Homepage" -> "https://bitbucket.org/clarolabdev/sonar-scala-plugin-test",
    "Plugin-License" -> "GNU LGPL 3",
    "Plugin-Version" -> "1.0.0-SNAPSHOT",
    "Implementation-Vendor" -> "com.clarotest.sonar",
    "Sonar-Version" -> "7.3",
    "Specification-Version" -> "1.0.0-SNAPSHOT",
    "Implementation-URL" -> "https://bitbucket.org/clarolabdev/sonar-scala-plugin-test",

  )
```

Let me know if you need any extra information, I'd be glad to provide you whatever you need from my end.

**Comment by h3xstream** [comment]
I know that the issue is close..

Just for reference the error comes from : `com.clarotest.sonar.`

`Caused by: java.lang.IllegalStateException: Unable to register extension com.clarotest.sonar.scala.Scala from plugin 'scalatest'`
