### ISSUE TITLE
sonar findbugs plugin 3.11.1 failing for Scala projects with SonarQube 7.9.1

### ISSUE THREAD

**Issue by subashiniunny** [spotbugs/sonar-findbugs#298]
## For a purely Scala project, Sonar analysis is failing with the following warning:
`WARN: Findbugs needs sources to be compiled. Please build project before executing sonar or check the location of compiled classes to make it possible for Findbugs to analyse your (sub)project.
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Can not execute Findbugs`

If we specify the `sonar.java.binaries` property passing the location of the Scala class files, it works fine. This was working without adding this property with SonarQube 6.7.5 and sonar-findbugs-plugin 3.9.3

Looks like this was an old issue that was fixed and is now broken again:
https://github.com/spotbugs/sonar-findbugs/issues/148

Log snippet:
`
13:10:29 INFO: Sensor FindBugs Sensor [findbugs]
13:10:31 INFO: JavaClasspath initialization
13:10:31 INFO: JavaClasspath initialization (done) | time=6ms
13:10:31 WARN: Findbugs needs sources to be compiled. Please build project before executing sonar or check the location of compiled classes to make it possible for Findbugs to analyse your (sub)project (......).
13:10:31 INFO: ------------------------------------------------------------------------
13:10:31 INFO: EXECUTION FAILURE
13:10:31 INFO: ------------------------------------------------------------------------
13:10:31 INFO: Total time: 13.898s
13:10:31 INFO: Final Memory: 44M/706M
13:10:31 INFO: ------------------------------------------------------------------------
13:10:31 ERROR: Error during SonarQube Scanner execution
13:10:31 java.lang.IllegalStateException: Can not execute Findbugs
13:10:31 	at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:188)
13:10:31 	at org.sonar.plugins.findbugs.FindbugsSensor.execute(FindbugsSensor.java:114)
13:10:31 	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
13:10:31 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
13:10:31 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
13:10:31 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
13:10:31 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
13:10:31 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
13:10:31 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
13:10:31 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
13:10:31 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
13:10:31 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
13:10:31 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:392)
13:10:31 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
13:10:31 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
13:10:31 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
13:10:31 	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
13:10:31 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
13:10:31 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
13:10:31 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
13:10:31 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:99)
13:10:31 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
13:10:31 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:10:31 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:10:31 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:10:31 	at java.lang.reflect.Method.invoke(Method.java:498)
13:10:31 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
13:10:31 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
13:10:31 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
13:10:31 	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
13:10:31 	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
13:10:31 	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
13:10:31 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
13:10:31 Caused by: java.lang.IllegalStateException: One (sub)project contains Java source files that are not compiled (/xxx/yyy/).
13:10:31 	at org.sonar.plugins.findbugs.FindbugsConfiguration.getFindbugsProject(FindbugsConfiguration.java:123)
13:10:31 	at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:119)`

## Environment

| Component           | Version |
| ------------------ | ------- |
| SonarQube             | 7.9.1   |
| Sonar-FindBugs     | 3.11.1  |
| Sonar scanner        | 3.0.3.778   |
| Scala                       | 2.11   |
| Maven                     | 3.5.3   |

**Comment by gtoison** [comment]
Scala code should be analyzed in the latest version (4.1.3) of the plugin, so please consider testing, this should fix the issue
Please let me know if there's any other problem
