### ISSUE TITLE
NullpointerException when executing analysis

### ISSUE THREAD

**Issue by Lonzak** [spotbugs/sonar-findbugs#305]
## Issue Description

We just did an upgrade to Sonar 7.9.1. Now during analysis we get the following Nullpointer during analysis:
```
13:41:20 [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.1.1688:sonar (default) on project our-project: null: MojoExecutionException: NullPointerException -> [Help 1]
13:41:20 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.1.1688:sonar (default) on project our-project: null
13:41:20 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
13:41:20 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
13:41:20 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
13:41:20 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
13:41:20 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
13:41:20 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
13:41:20 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
13:41:20 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
13:41:20 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
13:41:20 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
13:41:20 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13:41:20 	at java.lang.Thread.run(Thread.java:748)
13:41:20 Caused by: org.apache.maven.plugin.MojoExecutionException
13:41:20 	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:67)
13:41:20 	at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:104)
13:41:20 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
13:41:20 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
13:41:20 	... 11 more
13:41:20 Caused by: java.lang.NullPointerException
13:41:20 	at org.sonar.plugins.findbugs.FindbugsSensor.execute(FindbugsSensor.java:201)
13:41:20 	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
13:41:20 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
13:41:20 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
13:41:20 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
13:41:20 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
13:41:20 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
13:41:20 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
13:41:20 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
13:41:20 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
13:41:20 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
13:41:20 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:392)
13:41:20 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
13:41:20 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
13:41:20 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
13:41:20 	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
13:41:20 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
13:41:20 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
13:41:20 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
13:41:20 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
13:41:20 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
13:41:20 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:41:20 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:41:20 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:41:20 	at java.lang.reflect.Method.invoke(Method.java:498)
13:41:20 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
13:41:20 	at com.sun.proxy.$Proxy55.execute(Unknown Source)
13:41:20 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
13:41:20 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
13:41:20 	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:65)
13:41:20 	... 14 more
```

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.9.1   |
| Sonar-FindBugs     | 3.11.1   |
| Maven              | 3.3.9   |
| Java               | 1.8.0.191   |

## Code

```
//It seems that there is a null check is missing (like in line 222)
finally {
      classMappingWriter.flush();
      classMappingWriter.close();
    }

//should be 
    finally {
       if(classMappingWriter != null) {
         classMappingWriter.flush();
         classMappingWriter.close();
        }
    }
```

**Comment by Lonzak** [comment]
Added a PR for it 
https://github.com/spotbugs/sonar-findbugs/pull/306
