### ISSUE TITLE
Can not execute Findbugs with a timeout threshold value of 1200000 milliseconds

### ISSUE THREAD

**Issue by nenashevve** [spotbugs/sonar-findbugs#317]
SonarQube version
7.9
Description
Hello,
We get a timeout error (log below), but we have already increased the corresponding parameter (screenshot).
Please provide assistance in solving the problem, the analysis is running sonar-scanner-3.0.3.778

![Screen](https://user-images.githubusercontent.com/66992155/84743285-ec935a80-afdb-11ea-8f94-ce82631e30ef.jpg)

```
22:36:28  ERROR: Error during SonarQube Scanner execution
22:36:28  java.lang.IllegalStateException: Can not execute Findbugs with a timeout threshold value of 1200000 milliseconds
22:36:28  	at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:186)
22:36:28  	at org.sonar.plugins.findbugs.FindbugsSensor.execute(FindbugsSensor.java:114)
22:36:28  	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
22:36:28  	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
22:36:28  	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
22:36:28  	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
22:36:28  	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
22:36:28  	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
22:36:28  	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
22:36:28  	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
22:36:28  	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
22:36:28  	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
22:36:28  	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
22:36:28  	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
22:36:28  	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
22:36:28  	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
22:36:28  	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
22:36:28  	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
22:36:28  	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
22:36:28  	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:99)
22:36:28  	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
22:36:28  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:36:28  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22:36:28  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:36:28  	at java.lang.reflect.Method.invoke(Method.java:498)
22:36:28  	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
22:36:28  	at com.sun.proxy.$Proxy0.execute(Unknown Source)
22:36:28  	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
22:36:28  	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
22:36:28  	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
22:36:28  	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
22:36:28  	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
22:36:28  Caused by: java.util.concurrent.TimeoutException
22:36:28  	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
22:36:28  	at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:182)
22:36:28  	... 31 more
22:36:28  ERROR: 
22:36:28  ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
```

**Comment by gsepsupport** [comment]
Hi Team,

With Sonar 8.4 also facing the same issue even increased the timeout value.

Do you have any update on this please?

**Comment by deadstar2011** [comment]
Hello, team.
Any answer after 2 years?
@gtoison

**Comment by gtoison** [comment]
Sorry for the belated answer, the project was a bit abandonned and I've started maintaining it about a year ago
I'm running through the backlog of issues, but for this one there isn't nearly enough information here to diagnose what's happening.

From what I can see in that stacktrace the execution is stopped after the timeout expired but I have no idea why it took so long.

Information that would help troubleshooting:
- Versions (FindBugs plugin, SonarQube, JDK), if posible upgrade to the latest [4.2.0](https://github.com/spotbugs/sonar-findbugs/releases/tag/4.2.0)
- How is the analysis executed (Maven, Gradle, ...)?
- If not using Maven or Gradle, how is the `sonar.java.binaries` option set?
- Is the analysis also abnormaly long when using SpotBugs (i.e. is the issue in SpotBugs or in the plugin)?
- Some thread dumps taken before the timeout expires
- Some profiling data
- Attaching a debugger to the process and pausing it to see what seems to be taking too long
- Ideally a project I can use to reproduce the issue with
