### ISSUE TITLE
Sonarqube 7.9.4 analysis error on GCP cluster

### ISSUE THREAD

**Issue by yogesh206145** [spotbugs/sonar-findbugs#355]
Sonarqube 7.9.4 analysis error on GCP cluster

[sonar:sonar] Findbugs output report: /home/jenkins/agent/workspace/TestPipeline1/ABC-BuildDeploy/scripts/build/Wave_4.2.3/.scannerwork/findbugs-result.xml
BUILD FAILED
/home/jenkins/agent/workspace/TestPipeline1/ABC-BuildDeploy/scripts/build/Wave_4.2.3/W4.2.3-sonarbuild56.xml:86: javax.xml.stream.FactoryConfigurationError: Provider com.ibm.xml.xlxp.api.stax.XMLOutputFactoryImpl not found
	at javax.xml.stream.XMLOutputFactory.newInstance(Unknown Source)
	at com.thoughtworks.xstream.io.xml.StaxDriver.createOutputFactory(StaxDriver.java:250)
	at com.thoughtworks.xstream.io.xml.StaxDriver.getOutputFactory(StaxDriver.java:204)
	at com.thoughtworks.xstream.io.xml.StaxDriver.createWriter(StaxDriver.java:156)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1210)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1199)
	at org.sonar.plugins.findbugs.FindbugsConfiguration.exportProfile(FindbugsConfiguration.java:157)
	at org.sonar.plugins.findbugs.FindbugsConfiguration.saveIncludeConfigXml(FindbugsConfiguration.java:200)
	at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:147)
	at org.sonar.plugins.findbugs.FindbugsSensor.execute(FindbugsSensor.java:114) 

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.9.4  |
| Sonar-FindBugs     | 4.0.0   |
| ant                         |2.7.0.0.1612   |
| Java               | 8   |

**Comment by yogesh206145** [comment]
It was issue from our end. sonarscanner was looking for default xml parser which is resolved after adding it.
