### ISSUE TITLE
Findbugs hangs for a long time without producing logs and then exits with EmptyStackException error

### ISSUE THREAD

**Issue by darferrari** [spotbugs/sonar-findbugs#367]
## Issue Description

Hi, I'm having a issue with Findbugs: it has been a while since I ran the last sonar analysis using findbugs (on March 2021). The last time I used the plugin would elapse 20 minutes to produce the report to be sent to Sonarqube. I'm using the maven plugin for sonar-scanner and nothing has changed since then except the code to review. The main issue is that this is a multi-module project with cascade-style dependencies (the module after depends on the previous one) with millions lines of code. In particular, findbugs hangs on one of the biggest modules for more than a hour (sometimes even 5 hours)

```
[INFO] Loading findbugs plugin: /opt/jenkins/workspace/***/target/sonar/findbugs/sb-contrib.jar
[INFO] Loading findbugs plugin: /opt/jenkins/workspace/***/target/sonar/findbugs/findsecbugs-plugin.jar
[INFO] Findbugs output report: /opt/jenkins/workspace/***/findbugs-result.xml
```
It then interrupts the execution with an error, here there is the complete StackTrace that maven gave me using the -e switch:

```
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar (default-cli) on project ***: Can not execute Findbugs: java.util.EmptyStackException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar (default-cli) on project ***: Can not execute Findbugs
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Can not execute Findbugs
    at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute (ScannerBootstrapper.java:67)
    at org.sonarsource.scanner.maven.SonarQubeMojo.execute (SonarQubeMojo.java:108)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.IllegalStateException: Can not execute Findbugs
    at org.sonar.plugins.findbugs.FindbugsExecutor.execute (FindbugsExecutor.java:188)
    at org.sonar.plugins.findbugs.FindbugsSensor.execute (FindbugsSensor.java:114)
    at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse (AbstractSensorWrapper.java:48)
    at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute (ModuleSensorsExecutor.java:85)
    at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1 (ModuleSensorsExecutor.java:59)
    at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy (ModuleSensorsExecutor.java:77)
    at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute (ModuleSensorsExecutor.java:59)
    at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart (ModuleScanContainer.java:82)
    at org.sonar.core.platform.ComponentContainer.startComponents (ComponentContainer.java:137)
    at org.sonar.core.platform.ComponentContainer.execute (ComponentContainer.java:123)
    at org.sonar.scanner.scan.ProjectScanContainer.scan (ProjectScanContainer.java:393)
    at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively (ProjectScanContainer.java:389)
    at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively (ProjectScanContainer.java:386)
    at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart (ProjectScanContainer.java:358)
    at org.sonar.core.platform.ComponentContainer.startComponents (ComponentContainer.java:137)
    at org.sonar.core.platform.ComponentContainer.execute (ComponentContainer.java:123)
    at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart (GlobalContainer.java:144)
    at org.sonar.core.platform.ComponentContainer.startComponents (ComponentContainer.java:137)
    at org.sonar.core.platform.ComponentContainer.execute (ComponentContainer.java:123)
    at org.sonar.batch.bootstrapper.Batch.doExecute (Batch.java:72)
    at org.sonar.batch.bootstrapper.Batch.execute (Batch.java:66)
    at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute (BatchIsolatedLauncher.java:46)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke (IsolatedLauncherProxy.java:60)
    at com.sun.proxy.$Proxy25.execute (Unknown Source)
    at org.sonarsource.scanner.api.EmbeddedScanner.doExecute (EmbeddedScanner.java:189)
    at org.sonarsource.scanner.api.EmbeddedScanner.execute (EmbeddedScanner.java:138)
    at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute (ScannerBootstrapper.java:65)
    at org.sonarsource.scanner.maven.SonarQubeMojo.execute (SonarQubeMojo.java:108)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.util.concurrent.ExecutionException: java.util.EmptyStackException
    at java.util.concurrent.FutureTask.report (FutureTask.java:122)
    at java.util.concurrent.FutureTask.get (FutureTask.java:206)
    at org.sonar.plugins.findbugs.FindbugsExecutor.execute (FindbugsExecutor.java:182)
    at org.sonar.plugins.findbugs.FindbugsSensor.execute (FindbugsSensor.java:114)
    at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse (AbstractSensorWrapper.java:48)
    at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute (ModuleSensorsExecutor.java:85)
    at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1 (ModuleSensorsExecutor.java:59)
    at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy (ModuleSensorsExecutor.java:77)
    at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute (ModuleSensorsExecutor.java:59)
    at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart (ModuleScanContainer.java:82)
    at org.sonar.core.platform.ComponentContainer.startComponents (ComponentContainer.java:137)
    at org.sonar.core.platform.ComponentContainer.execute (ComponentContainer.java:123)
    at org.sonar.scanner.scan.ProjectScanContainer.scan (ProjectScanContainer.java:393)
    at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively (ProjectScanContainer.java:389)
    at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively (ProjectScanContainer.java:386)
    at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart (ProjectScanContainer.java:358)
    at org.sonar.core.platform.ComponentContainer.startComponents (ComponentContainer.java:137)
    at org.sonar.core.platform.ComponentContainer.execute (ComponentContainer.java:123)
    at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart (GlobalContainer.java:144)
    at org.sonar.core.platform.ComponentContainer.startComponents (ComponentContainer.java:137)
    at org.sonar.core.platform.ComponentContainer.execute (ComponentContainer.java:123)
    at org.sonar.batch.bootstrapper.Batch.doExecute (Batch.java:72)
    at org.sonar.batch.bootstrapper.Batch.execute (Batch.java:66)
    at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute (BatchIsolatedLauncher.java:46)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke (IsolatedLauncherProxy.java:60)
    at com.sun.proxy.$Proxy25.execute (Unknown Source)
    at org.sonarsource.scanner.api.EmbeddedScanner.doExecute (EmbeddedScanner.java:189)
    at org.sonarsource.scanner.api.EmbeddedScanner.execute (EmbeddedScanner.java:138)
    at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute (ScannerBootstrapper.java:65)
    at org.sonarsource.scanner.maven.SonarQubeMojo.execute (SonarQubeMojo.java:108)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.util.EmptyStackException
    at java.util.Stack.peek (Stack.java:102)
    at java.util.Stack.pop (Stack.java:84)
    at edu.umd.cs.findbugs.log.Profiler.end (Profiler.java:272)
    at edu.umd.cs.findbugs.FindBugs2.execute (FindBugs2.java:328)
    at org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call (FindbugsExecutor.java:235)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Before this error occurred, I stumbled across two errors, one given by the fact that there wasn't enough Java Heap space, one regarding the TimeoutException (extended the timeout to an unrealistic time, 6 hours)
I already have JVM heap memory expanded to min 500 MB and max 2048 MB and tried to play with Findbugs settings on the Sonarqube server, using minimal effort to find bugs and so on.
The issue seems related to the size of the module which contains a lot of dependencies and several java files, 1929.
The maven command I use to issue the analysis is the following:

```
mvn sonar:sonar -Dsonar.projectName=*** -e
```

Have you ever stumbled upon a scenario like that? 

| Component          | Version    |
| ------------------ | -----------  |
| SonarQube         | 8.5.1.38104 |
| Sonar-FindBugs     | 4.2.0   |
| Maven              | 3.6.3   |
| Java               | 8  |

**Comment by darferrari** [comment]
Update: the last pipeline I ran just hung until the timeout of 8 hours, after that it produced these errors:

```
Unable to find description of bug pattern IMC_IMMATURE_CLASS_BAD_SERIALVERSIONUID
  Unable to find description of bug pattern UCPM_USE_CHARACTER_PARAMETERIZED_METHOD
  Unable to find description of bug pattern COM_COPIED_OVERRIDDEN_METHOD
  Unable to find description of bug pattern SPP_USE_ISEMPTY
  Unable to find description of bug pattern USBR_UNNECESSARY_STORE_BEFORE_RETURN
  Unable to find description of bug pattern PSC_PRESIZE_COLLECTIONS
  Unable to find description of bug pattern PIS_POSSIBLE_INCOMPLETE_SERIALIZATION
  Unable to find description of bug pattern DRE_DECLARED_RUNTIME_EXCEPTION
  Unable to find description of bug pattern EXS_EXCEPTION_SOFTENING_NO_CONSTRAINTS
  Unable to find description of bug pattern LEST_LOST_EXCEPTION_STACK_TRACE
  Unable to find description of bug pattern MUI_CONTAINSKEY_BEFORE_GET
  Unable to find description of bug pattern USFW_UNSYNCHRONIZED_SINGLETON_FIELD_WRITES
  Unable to find description of bug pattern BL_BURYING_LOGIC
  Unable to find description of bug pattern SPP_TOSTRING_ON_STRING
  Unable to find description of bug pattern SCII_SPOILED_CHILD_INTERFACE_IMPLEMENTOR
  Unable to find description of bug pattern OCP_OVERLY_CONCRETE_PARAMETER
  Unable to find description of bug pattern LUI_USE_SINGLETON_LIST
  Unable to find description of bug pattern LSC_LITERAL_STRING_COMPARISON
  Unable to find description of bug pattern STT_STRING_PARSING_A_FIELD
  Unable to find description of bug pattern FCBL_FIELD_COULD_BE_LOCAL
  Unable to find description of bug pattern RFI_SET_ACCESSIBLE
  Unable to find description of bug pattern CLI_CONSTANT_LIST_INDEX
  Unable to find description of bug pattern LII_LIST_INDEXED_ITERATING
  Unable to find description of bug pattern NAB_NEEDLESS_BOX_TO_UNBOX
  Unable to find description of bug pattern OC_OVERZEALOUS_CASTING
  Unable to find description of bug pattern SPP_EMPTY_CASING
  Unable to find description of bug pattern UCC_UNRELATED_COLLECTION_CONTENTS
  Unable to find description of bug pattern CC_CYCLOMATIC_COMPLEXITY
  Unable to find description of bug pattern PCOA_PARTIALLY_CONSTRUCTED_OBJECT_ACCESS
  Unable to find description of bug pattern SEO_SUBOPTIMAL_EXPRESSION_ORDER
  Unable to find description of bug pattern LSYC_LOCAL_SYNCHRONIZED_COLLECTION
  Unable to find description of bug pattern NAB_NEEDLESS_BOXING_VALUEOF
  Unable to find description of bug pattern TBP_TRISTATE_BOOLEAN_PATTERN
  Unable to find description of bug pattern ISB_INEFFICIENT_STRING_BUFFERING
  Unable to find description of bug pattern MDM_BIGDECIMAL_EQUALS
  Unable to find description of bug pattern NAB_NEEDLESS_BOOLEAN_CONSTANT_CONVERSION
```

Could this be the cause?

**Comment by christopheroger** [comment]
Hello, have you found a solution ? it seeems I have a similar problem with sonarqube scanner on jenkins since I upgraded from sonar 7.9 to 8.9 LTS.

> INFO: ------------------------------------------------------------------------
> INFO: EXECUTION FAILURE
> INFO: ------------------------------------------------------------------------
> INFO: Total time: 52:03.771s
> INFO: Final Memory: 93M/1956M
> INFO: ------------------------------------------------------------------------
> ERROR: Error during SonarScanner execution
> java.lang.IllegalStateException: Can not execute Findbugs
> 	at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:188)
> 	at org.sonar.plugins.findbugs.FindbugsSensor.execute(FindbugsSensor.java:114)
> 	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
> 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
> 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
> 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
> 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
> 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
> 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
> 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:392)
> 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:388)
> 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:357)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
> 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
> 	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:150)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
> 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
> 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
> 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
> 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
> 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
> 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
> 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
> 	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
> 	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
> 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
> Caused by: java.util.concurrent.ExecutionException: java.util.EmptyStackException
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
> 	at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:182)
> 	... 31 more
> Caused by: java.util.EmptyStackException
> 	at java.util.Stack.peek(Stack.java:102)
> 	at java.util.Stack.pop(Stack.java:84)
> 	at edu.umd.cs.findbugs.log.Profiler.end(Profiler.java:272)
> 	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:328)
> 	at org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> ERROR: 
> ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.

- Sonar scanner: 4.4 (JDK 1.8)
- Sonarqube Server: 8.9.1 LTS / Findbugs plugin : 4.0.3

**Comment by darferrari** [comment]
Hello christopheroger,

I found a workaround by executing the scan in -X mode (debug) and forcing the execution of the scanner using one thread (it is not thread safe). By doing that, I was able to identify the java and class file that was causing the script to fail (it was stuck for an entire hour at that file). Basically what was happening was that the java file would explode the graph creation. I think that it was a memory error, 3 GB of heap didn't help.



Dario Ferrari

Blue Reply
Via Robert Koch, 1/4
20152 - Milano - ITALY
phone: +39 02 535761
***@***.******@***.***>
www.reply.it<http://www.reply.it> <http://>

[Blue Reply]
________________________________
