### ISSUE TITLE
ClassNotFoundException with sonarqube 9

### ISSUE THREAD

**Issue by nbegorre** [spotbugs/sonar-findbugs#368]
## Issue Description

After a clean install of Sonarqube 9, and the installation of sonar-findbugs 4.0.3, sonarqube do not restart due to NotClassDefFoundError. 
This seems link to the removal of org.sonar.api.profiles.ProfileDefinition from API (as stated on https://docs3.sonarqube.org/latest/extend/developing-plugin/)

```
java.lang.IllegalStateException: Fail to load plugin Findbugs [findbugs]
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:77)
        at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:575)
        at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:213)
        at org.sonar.server.platform.PlatformImpl.startLevel34Containers(PlatformImpl.java:187)
        at org.sonar.server.platform.PlatformImpl$1.lambda$doRun$0(PlatformImpl.java:120)
        at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:370)
        at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:120)
        at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:354)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/profiles/ProfileDefinition
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        at org.sonar.plugins.findbugs.FindbugsPlugin.define(FindbugsPlugin.java:60)
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:67)
        ... 8 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.profiles.ProfileDefinition
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        ... 22 common frames omitted

```

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 9.0.0.43356 |
| Sonar-FindBugs     | 4.0.3 |
| Java               | openjdk version "11.0.11" 2021-04-20   |

**Comment by tornstam** [comment]
I had the same problem upgrading to Sonarqube 9.0.0

**Comment by KengoTODA** [comment]
Please consider to submit a PR to fix. Recently I don't use SonarQube so have no opportunity to fix this.

BTW even though we fix it in this repo, we will need time to deliver it to marketplace, because recently SonarQube side doesn't handle the request to release for a half year...
https://community.sonarsource.com/t/new-release-findbugs-slf4j-1-5-0/36565/4

**Comment by gtoison** [comment]
@KengoTODA I have submitted a PR to replace the API references removed in Sonar 9.
Let me know if this helps

**Comment by ArnaudLec** [comment]
I just built and tried the PR on my 9.0.1 server and i'm having the following error while executing sonar:sonar :

`09:39:22  [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar (default-cli) on project [REDACTED]: org.sonar.plugins.findbugs.FindbugsConfiguration has unsatisfied dependency 'interface org.sonar.plugins.java.api.JavaResourceLocator' for constructor 'public org.sonar.plugins.findbugs.FindbugsConfiguration(org.sonar.api.batch.fs.FileSystem,org.sonar.api.config.Configuration,org.sonar.api.batch.rule.ActiveRules,org.sonar.plugins.java.api.JavaResourceLocator)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@2b82018:449<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@6e54bef6:64<| -> [Help 1]`

**Comment by gtoison** [comment]
During the refactor to remove usage of API removed in SQ 9 I have also replaced the deprecated `org.sonar.api.batch.ScannerSide` by `org.sonar.api.scanner.ScannerSide` in `FindBugsConfiguration` and `FindBugsProfileImporter`. The SQ javadoc just said to replace it but according to [this discussion](https://github.com/checkstyle/sonar-checkstyle/issues/194) it might be more complicated because the two annotations are not the same. In particular the JavaResourceLocator is apparently not injected with the new annotation.

@ArnaudLec could you please try reverting to using the deprecated org.sonar.api.batch.ScannerSide ? The plugin works for me on a 9.0.0 server but I'm not using the maven plugin

**Comment by ArnaudLec** [comment]
Ok tried with reverting to the old ScannerSide annotation and stubbled upon the following exception : 
```
Exception in thread "main" javax.xml.stream.FactoryConfigurationError: Provider for class javax.xml.stream.XMLOutputFactory cannot be created
	at java.xml/javax.xml.stream.FactoryFinder.findServiceProvider(FactoryFinder.java:366)
	at java.xml/javax.xml.stream.FactoryFinder.find(FactoryFinder.java:309)
	at java.xml/javax.xml.stream.FactoryFinder.find(FactoryFinder.java:222)
	at java.xml/javax.xml.stream.XMLOutputFactory.newInstance(XMLOutputFactory.java:138)
	at com.thoughtworks.xstream.io.xml.StaxDriver.createOutputFactory(StaxDriver.java:250)
	at com.thoughtworks.xstream.io.xml.StaxDriver.getOutputFactory(StaxDriver.java:204)
	at com.thoughtworks.xstream.io.xml.StaxDriver.createWriter(StaxDriver.java:156)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1238)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1227)
	at org.sonar.plugins.findbugs.FindbugsConfiguration.exportProfile(FindbugsConfiguration.java:179)
	at org.sonar.plugins.findbugs.FindbugsConfiguration.saveIncludeConfigXml(FindbugsConfiguration.java:228)
	at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:165)
        ...
Caused by: java.lang.RuntimeException: Provider for class javax.xml.stream.XMLOutputFactory cannot be created
	at java.xml/javax.xml.stream.FactoryFinder.findServiceProvider(FactoryFinder.java:363)
	... 64 more
Caused by: java.util.ServiceConfigurationError: javax.xml.stream.XMLOutputFactory: Provider com.ctc.wstx.stax.WstxOutputFactory not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
```
Not so surprising because native plugins classes are no longer accessible from other plugins.

I added the com.fasterxml.woodstox:woodstox-core:5.2.0 as a dependency and everything works, the findbugs issues are back.

**Comment by gtoison** [comment]
@ArnaudLec thanks for confirming the issue with the ScannerSide annotation
Regarding the woodstox dependency problem I'm not sure what might have changed in SQ 9 and also why I did not encounter this error. Would you be able to share a way to reproduce the error?

**Comment by ArnaudLec** [comment]
I fiddled with the pom file by adding 
```
    <dependency>
      <groupId>org.sonarsource.java</groupId>
      <artifactId>java-frontend</artifactId>
      <version>${sonar-java.version}</version>
      <scope>provided</scope>
    </dependency>
```
and
```
<basePlugin>java</basePlugin>
```
in sonar-packaging-maven-plugin to test things, to look like my custom java rules plugin.
Maybe that comes from it.
