### ISSUE TITLE
java.lang.IllegalStateException: Can not execute Findbugs

### ISSUE THREAD

**Issue by vbhvjari** [spotbugs/sonar-findbugs#388]
## Issue Description

We are using Sonar-FindBugs 4.0.3 plugin for SonarQube 7.9.6.
Sonar scan is getting failed with below errors:

```
18:00:25  [2021-09-09T16:00:10.204Z] 09:00:10.203 WARN: Findbugs needs sources to be compiled. Please build project before executing sonar or check the location of compiled classes to make it possible for Findbugs to analyse your (sub)project (/workspace/sdk).
18:00:25  [2021-09-09T16:00:10.213Z] 09:00:10.213 INFO: ------------------------------------------------------------------------
18:00:25  [2021-09-09T16:00:10.213Z] 09:00:10.213 INFO: EXECUTION FAILURE
18:00:25  [2021-09-09T16:00:10.213Z] 09:00:10.213 INFO: ------------------------------------------------------------------------
18:00:25  [2021-09-09T16:00:10.213Z] 09:00:10.213 INFO: Total time: 55.471s
18:00:25  [2021-09-09T16:00:10.294Z] 09:00:10.293 ERROR: Error during SonarScanner execution
18:00:25  [2021-09-09T16:00:10.294Z] 09:00:10.293 INFO: Final Memory: 28M/114M
18:00:25  [2021-09-09T16:00:10.294Z] 09:00:10.293 INFO: ------------------------------------------------------------------------
18:00:25  [2021-09-09T16:00:10.294Z] java.lang.IllegalStateException: Can not execute Findbugs
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:188)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.plugins.findbugs.FindbugsSensor.execute(FindbugsSensor.java:114)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
18:00:25  [2021-09-09T16:00:10.294Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:00:25  [2021-09-09T16:00:10.294Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
18:00:25  [2021-09-09T16:00:10.294Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
18:00:25  [2021-09-09T16:00:10.294Z] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
18:00:25  [2021-09-09T16:00:10.294Z] 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
18:00:25  [2021-09-09T16:00:10.294Z] Caused by: java.lang.IllegalStateException: One (sub)project contains Java source files that are not compiled (/workspace/sdk).
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.plugins.findbugs.FindbugsConfiguration.getFindbugsProject(FindbugsConfiguration.java:123)
18:00:25  [2021-09-09T16:00:10.294Z] 	at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:119)
18:00:25  [2021-09-09T16:00:10.294Z] 	... 31 more
```

The project is being compiled before running the scanner, so I am not sure why it's still asking for the bytecoded files.

**Comment by gtoison** [comment]
Hello,
It would be great if you could share the structure of the project you're trying to analyse
You can try looking into this similar issue: https://github.com/spotbugs/sonar-findbugs/issues/323
Otherwise you can also experiment with the "Allow Uncompiled Code" configuration option for the plugin

**Comment by jooeji** [comment]
where is  "Allow Uncompiled Code" configuration  option for the plugin?

**Comment by gtoison** [comment]
@jooeji the setting is on the server under Administration / Configuration / Languages / Java
or set it at project level with `sonar.findbugs.allowuncompiledcode`.

Would you mind sharing the structure of the project you're trying to analyze? I'm trying to add integrations tests and it would be helpful to know what kind of project you're analyzing.


![image](https://user-images.githubusercontent.com/86775455/144827605-c7f27249-da47-42c3-ae4d-226f7dc78606.png)
