### ISSUE TITLE
BadRequestException: scala rule findsecbugs-scala:SCALA_XSS_MVC_API cannot be activated on java profile FindBugs Security Audit

### ISSUE THREAD

**Issue by gtjarks** [spotbugs/sonar-findbugs#516]
## Issue Description
SonarQube does not start with Sonar-FindBugs 4.1.0 see log.

## Environment
| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 9.4 (build 54424)   |
| Sonar-FindBugs     | 4.1.0   |

LOG:
```java
2022.04.19 06:51:16 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile java/FindBugs Security Audit
2022.04.19 06:51:16 WARN  web[][o.s.c.a.AnnotationConfigApplicationContext] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jdk.internal.loader.ClassLoaders$AppClassLoader@55054057-org.sonar.server.qualityprofile.RegisterQualityProfiles': Initialization of bean failed; nested exception is BadRequestException{errors=[scala rule findsecbugs-scala:SCALA_XSS_MVC_API cannot be activated on java profile FindBugs Security Audit]}
2022.04.19 06:51:16 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jdk.internal.loader.ClassLoaders$AppClassLoader@55054057-org.sonar.server.qualityprofile.RegisterQualityProfiles': Initialization of bean failed; nested exception is BadRequestException{errors=[scala rule findsecbugs-scala:SCALA_XSS_MVC_API cannot be activated on java profile FindBugs Security Audit]}
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:187)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:80)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:51)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:119)
	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:45)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:116)
	at org.sonar.server.platform.PlatformImpl.executeStartupTasks(PlatformImpl.java:183)
	at org.sonar.server.platform.PlatformImpl$1.lambda$doRun$1(PlatformImpl.java:107)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:344)
	at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:107)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:328)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.sonar.server.exceptions.BadRequestException: scala rule findsecbugs-scala:SCALA_XSS_MVC_API cannot be activated on java profile FindBugs Security Audit
	at org.sonar.server.exceptions.BadRequestException.create(BadRequestException.java:57)
	at org.sonar.server.exceptions.BadRequestException.create(BadRequestException.java:61)
	at org.sonar.server.exceptions.BadRequestException.checkRequest(BadRequestException.java:44)
	at org.sonar.server.qualityprofile.builtin.RuleActivator.doActivate(RuleActivator.java:95)
	at org.sonar.server.qualityprofile.builtin.RuleActivator.activate(RuleActivator.java:88)
	at org.sonar.server.qualityprofile.builtin.RuleActivator.lambda$activate$0(RuleActivator.java:81)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.sonar.server.qualityprofile.builtin.RuleActivator.activate(RuleActivator.java:83)
	at org.sonar.server.qualityprofile.builtin.BuiltInQProfileUpdateImpl.update(BuiltInQProfileUpdateImpl.java:79)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.update(RegisterQualityProfiles.java:138)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.lambda$start$1(RegisterQualityProfiles.java:99)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.start(RegisterQualityProfiles.java:94)
	at org.sonar.core.platform.StartableBeanPostProcessor.postProcessBeforeInitialization(StartableBeanPostProcessor.java:33)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	... 20 common frames omitted
```

**Comment by ArnaudLec** [comment]
Same here.
Rollbacked to 4.0.6.

**Comment by gtoison** [comment]
Thank you for reporting the issue and sorry about that.
I was unfortunately unable to reproduce it but I think I know what's happening. I've made a pre-release here: https://github.com/spotbugs/sonar-findbugs/releases/tag/4.1.1
Can you please try it out and let me know if it's any better?

I'll try to find out why this bug did not show up in the integration tests

**Comment by gtoison** [comment]
Right, so I was able to reproduce the bug by upgrading the plugin to version 4.1.0
The integrations tests use a fresh install of SonarQube so they missed this scenario, that's definitively something to add to the tests suite.
The issue did not happen with version 4.1.1 available [here](https://github.com/spotbugs/sonar-findbugs/releases) so please try that one and let me know if there's any problem

**Comment by janosvitok** [comment]
I've installed 4.1.1 on a sonarqube instance that had 4.0.6 (worked) upgraded to 4.1.0 (sonar didn't start), then downgraded back to 4.0.6 (working again). With 4.1.1 sonarqube started fine and also analysis went OK.

**Comment by gtoison** [comment]
Thanks for testing @janosvitok , so 4.1.1 is the good version
I've just added some integration tests reproducing the issue so hopefully this shouldn't happen again!

**Comment by ArnaudLec** [comment]
Same here, 4.1.1 fixed the startup error.

Thank you.

**Comment by gtoison** [comment]
Thank you for confirming @ArnaudLec 
I've made a proper release as version 4.1.3
The only difference with 4.1.1 are the new unit and integration tests so there's nothing new on the plugin itself. 
In case you're wondering version 4.1.2 was skipped because I made an error in the release process
