### ISSUE TITLE
Findbugs plugin fails to analyse java project

### ISSUE THREAD

**Issue by alok347** [spotbugs/sonar-findbugs#534]
```
INFO: Sensor FindBugs Sensor [findbugs]
22:03:24  INFO: Loading findbugs plugin: <path>/.scannerwork/findbugs/findsecbugs-plugin.jar
22:03:24  INFO: Findbugs output report: <path>/.scannerwork/findbugs-result.xml
22:03:24  The following errors occurred during analysis:
22:03:24    Error scanning abc/abc/abc for referenced classes
22:03:24      java.lang.IllegalArgumentException: Unsupported class file major version 61
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
22:03:24        At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
22:03:24        At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
22:03:24        At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
22:03:24        At edu.umd.cs.findbugs.FindBugs2.buildReferencedClassSet(FindBugs2.java:806)
22:03:24        At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:249)
22:03:24        At org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)
22:03:24        At java.base/java.util.concurrent.FutureTask.run(Unknown Source)
22:03:24        At java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
22:03:24        At java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
22:03:24        At java.base/java.lang.Thread.run(Unknown Source)
22:03:24    Error scanning xcv/xcv/xcv/xcv for referenced classes
22:03:24      java.lang.IllegalArgumentException: Unsupported class file major version 61
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
22:03:24        At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
22:03:24        At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
22:03:24        At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
22:03:24        At edu.umd.cs.findbugs.FindBugs2.buildReferencedClassSet(FindBugs2.java:806)
22:03:24        At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:249)
22:03:24        At org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)
22:03:24        At java.base/java.util.concurrent.FutureTask.run(Unknown Source)
22:03:24        At java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
22:03:24        At java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
22:03:24        At java.base/java.lang.Thread.run(Unknown Source)
22:03:24    Error scanning xyz/xyz/xyz for referenced classes
22:03:24      java.lang.IllegalArgumentException: Unsupported class file major version 61
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
22:03:24        At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
22:03:24        At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
22:03:24        At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
22:03:24        At edu.umd.cs.findbugs.FindBugs2.buildReferencedClassSet(FindBugs2.java:806)
22:03:24        At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:249)
22:03:24        At org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)
22:03:24        At java.base/java.util.concurrent.FutureTask.run(Unknown Source)
22:03:24        At java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
22:03:24        At java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
22:03:24        At java.base/java.lang.Thread.run(Unknown Source)
22:03:24    Error scanning abc/abc/abc for referenced classes
22:03:24      java.lang.IllegalArgumentException: Unsupported class file major version 61
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
22:03:24        At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
22:03:24        At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
22:03:24        At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
22:03:24        At edu.umd.cs.findbugs.FindBugs2.buildReferencedClassSet(FindBugs2.java:806)
22:03:24        At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:249)
22:03:24        At org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)
22:03:24        At java.base/java.util.concurrent.FutureTask.run(Unknown Source)
22:03:24        At java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
22:03:24        At java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
22:03:24        At java.base/java.lang.Thread.run(Unknown Source)
22:03:24    Error scanning xxx/xxx/xxx/ for referenced classes
22:03:24      java.lang.IllegalArgumentException: Unsupported class file major version 61
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
22:03:24        At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
22:03:24        At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
22:03:24        At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
22:03:24        At edu.umd.cs.findbugs.FindBugs2.buildReferencedClassSet(FindBugs2.java:806)
22:03:24        At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:249)
22:03:24        At org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)
22:03:24        At java.base/java.util.concurrent.FutureTask.run(Unknown Source)
22:03:24        At java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
22:03:24        At java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
22:03:24        At java.base/java.lang.Thread.run(Unknown Source)
22:03:24    Error scanning xxx/xxx/xxx for referenced classes
22:03:24      java.lang.IllegalArgumentException: Unsupported class file major version 61
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
22:03:24        At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
22:03:24        At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
22:03:24        At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
22:03:24        At edu.umd.cs.findbugs.FindBugs2.buildReferencedClassSet(FindBugs2.java:806)
22:03:24        At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:249)
22:03:24        At org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)
22:03:24        At java.base/java.util.concurrent.FutureTask.run(Unknown Source)
22:03:24        At java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
22:03:24        At java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
22:03:24        At java.base/java.lang.Thread.run(Unknown Source)
22:03:24    Error scanning xx/xxx/xxx/xxx for referenced classes
22:03:24      java.lang.IllegalArgumentException: Unsupported class file major version 61
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
22:03:24        At org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
22:03:24        At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
22:03:24        At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
22:03:24        At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
22:03:24        At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
22:03:24        At edu.umd.cs.findbugs.FindBugs2.buildReferencedClassSet(FindBugs2.java:806)
22:03:24        At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:249)
22:03:24        At org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)
22:03:24        At java.base/java.util.concurrent.FutureTask.run(Unknown Source)
22:03:24        At java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
22:03:24        At java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
22:03:24        At java.base/java.lang.Thread.run(Unknown Source)
22:03:25  Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: edu.umd.cs.findbugs.NoClassesFoundToAnalyzeException: No classes found to analyze in <path>
22:03:25  Caused by: java.lang.RuntimeException: edu.umd.cs.findbugs.NoClassesFoundToAnalyzeException: No classes found to analyze in <path>
22:03:25  	at com.google.common.base.Throwables.propagate(Throwables.java:240)
22:03:25  	at org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:238)
22:03:25  	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
22:03:25  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
22:03:25  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
22:03:25  	at java.base/java.lang.Thread.run(Unknown Source)
22:03:25  	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:304)
22:03:25  	at org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)
22:03:25  	... 4 more
22:03:25  ERROR: 
22:03:25  ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
```

We are using findbugs plugin version 4.0.1 on SonarQube 7.9.4 version. Recently the java project analysis failed with the above errors.
Please let us know the cause of failure of this plugin and if this can be fixed ?
Its a blocker for our team, hence request your support on this one.

Regards,
Alok Singh

**Comment by gtoison** [comment]
Hello,
You need to upgrade to findbugs plugin version 4.0.6 or (just released) 4.1.4 to get Java 17 support
SonarQube 7.9.4 is no longer supported by SonarSource so you might wan to upgrade to 8.9 at the same time

**Comment by alok347** [comment]
HI @gtoison ,

Thanks for the update. 
We will test the latest plugin on QA application first. However, would like to know if there are projects compiled with java 8 and java 11 should not be impacted by updating the plugin to latest 4.1.4 version right?

Regards,
Alok Singh

**Comment by gtoison** [comment]
It should support java 8 or 11, actually if you upgrade to 4.1.5 the support should go through java 19

**Comment by alok347** [comment]
Okay, Thanks.

**Comment by alok347** [comment]
Hi @gtoison ,

Yes upgrading the plugin resolved the issue. However, one of the team reported increase in overall code smell for their multiple projects. They are using findbugs plugin during the analysis.

These code smells have raised issues in the old files which were not analysed recently and marked them as old issues.

Do you think there's a possibility that the upgraded plugin might have highlighted issues which were previously not listed in SonarQube? The quality profile used by the team is not of a findbugs plugin but a custom quality profile build using sonarway inbuilt Quality Profile.

Do Findbugs plugin uses the default java rules that comes with the application or findbugs plugin comes with its own rules?

Note:Team says they have not changed anything in these files.

Regards,
Alok Singh

**Comment by gtoison** [comment]
The plugin uses [SpotBugs](https://github.com/spotbugs/spotbugs) under the hood and converts its findings into SonarQube issues.
When you have upgraded the plugin you have upgraded the SpotBugs version at the same time. New versions include new rules that might or might not be activated depending on your quality profile. It is also possible that changes in SpotBugs create some false positives.
If you also upgraded SonarQube itself the native rules will also change and will detect bugs in old code.

So yes, it is definitively possible that upgrading the plugin caused some new bugs to be detected. If you can give me some examples of rules I can look into it.

**Comment by alok347** [comment]
Hi @gtoison ,

Thank you for sharing the update. It took me some time to find few rules that are used during the project analysis.
Would it be possible for you to let me know if these are part of the rules that were updated recently:

1. Malicious code - May expose internal representation by incorporating reference to mutable object
2. Malicious code - May expose internal representation by returning reference to mutable object
3. Malicious code - May expose internal static state by storing a mutable object into a static field
4. Malicious code - Public static method may expose internal representation by returning array

The Findbug rules used in their Quality Profile are as below including these:

`	
Malicious code - An overridable method is called from a constructor

Malicious code - An overridable method is called from the clone() method.

Malicious code - Custom class loader does not call its superclass's getPermissions()

Malicious code - May expose internal representation by creating a buffer which incorporates reference to array

Malicious code - May expose internal representation by returning a buffer sharing non-public data

Malicious code - May expose internal representation by returning a buffer sharing non-public data

Malicious code - May expose internal static state by creating a buffer which stores an external array into a static field

Malicious code - Potential security check based on untrusted source.

Malicious code - Public method uses reflection to create a class it gets in its parameter which could increase the accessibility of any class

Malicious code - Public method uses reflection to modify a field it gets in its parameter which could increase the accessibility of any class  `


Regards,
Alok Singh

**Comment by gtoison** [comment]
You were on version 4.0.1 of the plugin which was internally using SpotBugs 4.1.2
The SpotBugs rule codes are visible in SonarQube as the key of the rule:
![image](https://user-images.githubusercontent.com/86775455/173008583-f8cb8c6d-ff37-4380-9b44-e809f5a04c97.png)

The changes in SpotBug are available [here ](https://github.com/spotbugs/spotbugs/blob/master/CHANGELOG.md) and you can look for changes in these rules between SpotBugs 4.1.2 through 4.7.0

**Comment by gtoison** [comment]
I'll close this since there does not seem to be further questions, please don't hesitate to open a new issue
