### ISSUE TITLE
Error: java.lang.IllegalStateException: One (sub)project contains Java source files that are not compiled (/home/jenkins/agent/workspace/cationgateway_multibranch_master).

### ISSUE THREAD

**Issue by mvijay21** [spotbugs/sonar-findbugs#559]
## Issue Description

Since after upgrade to SonarQube v8.9.7 the findbugs causing the error failing with the findbugs needs sources to be compiled. Please build project before executing sonar or check the location of compiled classes to make it possible for Findbugs to analyse your (sub)project 
```
INFO: 8/8 source files have been analyzed
INFO: Sensor Kotlin Sensor [kotlin] (done) | time=1697ms
INFO: Sensor KotlinSurefireSensor [kotlin]
INFO: parsing [/home/jenkins/agent/workspace/cationgateway_multibranch_master/target/surefire-reports]
INFO: Sensor KotlinSurefireSensor [kotlin] (done) | time=1ms
INFO: Sensor ThymeLeaf template sensor [securityjavafrontend]
INFO: javasecurity:S5131 is not activated in quality profile: skipping execution of thymeleaf sensor.
INFO: Sensor ThymeLeaf template sensor [securityjavafrontend] (done) | time=0ms
INFO: Sensor FindBugs Sensor [findbugs]
WARN: Findbugs needs sources to be compiled. Please build project before executing sonar or check the location of compiled classes to make it possible for Findbugs to analyse your (sub)project (/home/jenkins/agent/workspace/cationgateway_multibranch_master).
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 30.668s
INFO: Final Memory: 59M/212M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: Can not execute Findbugs
	at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:188)
	at org.sonar.plugins.findbugs.FindbugsSensor.execute(FindbugsSensor.java:126)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:392)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:388)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:357)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:150)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.IllegalStateException: One (sub)project contains Java source files that are not compiled (/home/jenkins/agent/workspace/cationgateway_multibranch_master).
	at org.sonar.plugins.findbugs.FindbugsConfiguration.initializeFindbugsProject(FindbugsConfiguration.java:123)
	at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:117)
	... 31 more
ERROR: 
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
```

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 8.9.7  |
| Sonar-FindBugs     | 4.1.5   |
| Gradle             | 6.8.3   |
| Java               | 11   |

## Code (If needed)

Sonar.project.Properties file:

```
sonar.projectKey=com.ford:dropfire-Service14
sonar.projectName=dropfire-service-cvnotificationgateway
sonar.coverage.exclusions=**/*Application.java,**/configs/*.java,**/data/*.java,**/model/*.java,**/configuration/*.java,**/dao/*.java,**/common/*.java,**/util/ErrorModelBuilderforPush.java
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=build/classes
sonar.test.inclusions=**/*test*/**
sonar.exclusions=**/*test*/**,**/model/*.java,**/util/ErrorModelBuilderforPush.java

sonar.core.codeCoveragePlugin=jacoco
sonar.language=java,kotlin
sonar.coverage.jacoco.xmlReportPaths=build/jacoco/report.xml
```

**Comment by gtoison** [comment]
SpotBugs works by analyzing the .class files (not the java source files), the error messages indicates that it could not find any .class file
Only the .class files corresponding to .java files analyzed in the project are considered.

Based on your configuration my guess would be that:
- `build/classes` does not contain any .class file because the project was not built
- or all the corresponding .java files are excluded in `sonar.exclusions`

Could you please make sure that the project is built (and that the .class files are in the `build/classes` folder) and try again without the `sonar.exclusions` option?

**Comment by mvijay21** [comment]
Tried the local build and all the .class files are present at the build/classes path .
We tried the build after removing the sonar.exclusion option,  its still failing due to same issue. Attached are the logs.
Please advise us on the next steps.

[Sonarnew.log](https://github.com/spotbugs/sonar-findbugs/files/8780690/Sonarnew.log)

**Comment by gtoison** [comment]
Sorry, I think I got confused and it says `INFO: 109/109 source files have been analyzed`, the part I was looking at was for the test code.

I'm still not sure what's causing the issue but I've released a fix in version 4.1.6, can you please try upgrading and let me know if it's any better? The plugin jar is here: https://github.com/spotbugs/sonar-findbugs/releases/download/4.1.6/sonar-findbugs-plugin-4.1.6.jar

**Comment by mvijay21** [comment]
@gtoison Please accept my apologies for the delayed response. After installing the new plugin, the problem was resolved. Thank you so much for your help. This 4.1.6 should be compatible with the SonarQube 8.9.7 LTS version.

**Comment by mvijay21** [comment]
@gtoison We're from the tools team, and we're managing the SonarQube tool for our PDO team. This problem was reported by one of our customers. They are included in the gradle build project.
After testing this plugin in the lower environment with the teams that were experiencing the error (source code not compiled) that got fixed, so we applied this plugin in the production on last weekend, Today we received a mail from the PDO teams saying that their issue count had suddenly increased.

When I look at their issues, almost all of them have critical severity.

Malicious code - May expose internal representation by incorporating reference to mutable object

Any support pls?

**Comment by gtoison** [comment]
I suspect this is linked to this changed in SpotBugs: https://github.com/spotbugs/spotbugs/blob/master/CHANGELOG.md#430---2021-07-01
This was incorporated since version 4.0.4 of the Sonar Findbugs plugin, so if you upgraded from an earlier version that would explain the new issues.

If they think these are false positives they can report the issue to the [SpotBugs project](https://github.com/spotbugs/spotbugs/issues) or if they are not relevant they can probably disable the rule in their quality profile

**Comment by mvijay21** [comment]
@gtoison The production SonarQube version was upgraded from 7.9 LTS (sonar-findbugs - 4.0.0) to 8.9 LTS Version (sonar-findbugs- 4.1.6), so you saying that causing this problem.

Question:

How do I handle the false positive issue?
If I wish to disable the rule, how do I locate it in the quality profile and deactivate it?

please guide..

**Comment by gtoison** [comment]
There are multiple ways to disable a rule if it's not relevant: https://stackoverflow.com/questions/16399311/disable-rule-in-sonar
But I'm not saying it is a false positive, it might very well be an actual problem detected in the code

**Comment by mvijay21** [comment]
@gtoison I found something on the issues raised on the code smells (tag: malicious-code) all of the severity it displays as INFO, but when I check the quality profiles, using the same rule throws as critical.

I'm guessing that's why the teams using the quality profile suddenly see the spike on the issue after I installed the latest find bugs plugin on the server.

Do you know why the rule severity isn't inheriting to the quality profiles that use the same rule? Is there anything we need to do manually?

**Comment by gtoison** [comment]
The built-in quality profiles have an INFO severity for this rule, but someone might have configured a custom profile where it's CRITICAL for your server. You need to look into how your quality profiles are setup, but that's a bit beyond the scope of this project

**Comment by gtoison** [comment]
I'll close this since there does not seem to be further question, please don't hesitate to open a new issue
