### ISSUE TITLE
java.lang.IllegalStateException: Can not execute Findbugs

### ISSUE THREAD

**Issue by anbha15** [spotbugs/sonar-findbugs#594]
## Issue Description

Our java code is based on java 1.8 and built by gradle. We can not migrate java code to java 11 immediately. But we are doing code analysis with sonarqube server version 9.4 which supports minimum JDK 11. So github action with sonar scan is failing.
in our case gradle build should be with java 8 but sonar scan should be with java 11.

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 9.4   |
| Sonar-FindBugs     | ?????   |
| Maven              | ?????   |
| Gradle             | 6.0.1   |
| Java               | 1.8   |

## Code (If needed)
Below github action is calling the reusable workflow attached in the attachment and triggering the gradle build and sonar scan.
-----
  build-gradle-sonar:
    uses: ingka-group-digital/cssbr-common-workflows/.github/workflows/build-gradle-sonar.yml@3491
    secrets:
      artifactoryUsername: ${{ secrets.ARTIFACTORYUSERNAME }}
      artifactoryPassword: ${{ secrets.ARTIFACTORYPASSWORD }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
    with:
      projectKey: cssbr.be-time-window.java
      projectName: CSSBR-BE-TIME-WINDOW-JAVA
      sourceFolder: src/main
--------------
See the attached folder. here you can find different combination of github action reusable workflow with corresponding error logs for sonar scan. 

[folder_not_working.zip](https://github.com/spotbugs/sonar-findbugs/files/9081918/folder_not_working.zip)

`

**Comment by gtoison** [comment]
Hello,

The relevant error message from the SpotBugs plugin is:

```
2022-07-08T09:44:57.3225159Z Caused by: java.lang.IllegalStateException: One (sub)project contains Java source files that are not compiled (/github/workspace).
2022-07-08T09:44:57.3225816Z 	at org.sonar.plugins.findbugs.FindbugsConfiguration.initializeFindbugsProject(FindbugsConfiguration.java:123)
2022-07-08T09:44:57.3226639Z 	at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:117)
2022-07-08T09:44:57.3227004Z 	... 31 more
```

SpotBugs analyzes the compiled `.class` files, if they do not exist it won't work and will return that error.

In your logs I see a lot of compile errors, for instance:
```
2022-07-08T09:20:25.0049585Z /home/runner/work/css-be-time-window/css-be-time-window/src/main/java/se/centiro/facade/otherservices/_8/datacontract/Attribute.java:4: error: package javax.xml.bind does not exist
2022-07-08T09:20:25.0050470Z import javax.xml.bind.JAXBElement;
```
That would explain why the `.class` files cannot be found and in any case you should probably solve these compilation errors first.

I also see that SonarQube's native Java plugin is complaining that the class files are missing:

```
2022-07-08T09:32:43.6011372Z INFO: Sensor JavaSensor [java]
2022-07-08T09:32:43.6175590Z INFO: Configured Java source version (sonar.java.source): none
2022-07-08T09:32:43.6306516Z INFO: JavaClasspath initialization
2022-07-08T09:32:43.6329541Z ERROR: Invalid value for 'sonar.java.binaries' property.
2022-07-08T09:32:43.6582797Z INFO: ------------------------------------------------------------------------
2022-07-08T09:32:43.6583176Z INFO: EXECUTION FAILURE
2022-07-08T09:32:43.6583576Z INFO: ------------------------------------------------------------------------
2022-07-08T09:32:43.6589509Z INFO: Total time: 49.517s
2022-07-08T09:32:43.7462021Z ERROR: Error during SonarScanner execution
2022-07-08T09:32:43.7462346Z INFO: Final Memory: 33M/114M
2022-07-08T09:32:43.7462954Z INFO: ------------------------------------------------------------------------
2022-07-08T09:32:43.7466090Z java.lang.IllegalStateException: No files nor directories matching 'build/classes'
2022-07-08T09:32:43.7473467Z 	at org.sonar.java.classpath.AbstractClasspath.getFilesFromProperty(AbstractClasspath.java:128)
2022-07-08T09:32:43.7477141Z 	at org.sonar.java.classpath.ClasspathForMain.init(ClasspathForMain.java:58)
2022-07-08T09:32:43.7480737Z 	at org.sonar.java.classpath.AbstractClasspath.getElements(AbstractClasspath.java:319)
2022-07-08T09:32:43.7484036Z 	at org.sonar.java.SonarComponents.getJavaClasspath(SonarComponents.java:203)
2022-07-08T09:32:43.7487659Z 	at org.sonar.java.JavaFrontend.<init>(JavaFrontend.java:93)
```

**Comment by anbha15** [comment]
Hi,
This build errors can be ignored. You see the last message where it writes build is success. The same build error worked with sonar 8.9 using Java 8 whereas it is throwing error while using sonar server 9.4 using java 11. I am attaching the success log and corresponding github action for your reference when I used JDK 1.8 for both gradle build and sonar scan with soan server version 8.9. The issue I am facing now is that java code gradle build will be with JDK 1.8 which is success whereas sonar scan should be run with sonar server 9.4 supporting JDK 1.11 which is throwing error.

[folder_working.zip](https://github.com/spotbugs/sonar-findbugs/files/9084117/folder_working.zip)


Thanks,
Anirban

**Comment by gtoison** [comment]
The SpotBugs plugin does not use directly the `sonar.java.binaries`, it uses SonarQube's native Java plugin to get the "classes to analyze", in turn SonarQube uses `sonar.java.binaries`
The usual way to run the scanner is by using Gradle's Sonar plugin. When used that way, the Sonar plugin automatically sets `sonar.java.binaries`. This helps making sure that it points to the folder(s) where gradle put the compiled `.class` files and you just need to run `gradle build sonarqube`

Your build seems to build the project, upload the artifacts, download the artifact and run the sonar CLI scanner. I'm not sure how this works (or why it's done) and it's a bit complicated for me to troubleshoot what might be happening.
Your logs say:
```
2022-07-12T10:30:40.2850102Z Artifact my-artifact was downloaded to /home/runner/work/css-be-time-window/css-be-time-window/build/classes
```

And then:
```
2022-07-12T10:31:40.3216032Z INFO: Working dir: /github/workspace/.scannerwork
...
2022-07-12T10:32:21.5637876Z Caused by: java.lang.IllegalStateException: One (sub)project contains Java source files that are not compiled (/github/workspace).
```
Maybe the artifacts are downloaded in the wrong folder?

You also seemed to have a build failing where the SonarQube native Java plugin says that there are not files, so that might explain the problem, even if the property is set it does not mean that it's going to work.

```
2022-07-08T09:32:43.6011372Z INFO: Sensor JavaSensor [java]
2022-07-08T09:32:43.6175590Z INFO: Configured Java source version (sonar.java.source): none
2022-07-08T09:32:43.6306516Z INFO: JavaClasspath initialization
2022-07-08T09:32:43.6329541Z ERROR: Invalid value for 'sonar.java.binaries' property.
2022-07-08T09:32:43.6582797Z INFO: ------------------------------------------------------------------------
2022-07-08T09:32:43.6583176Z INFO: EXECUTION FAILURE
2022-07-08T09:32:43.6583576Z INFO: ------------------------------------------------------------------------
2022-07-08T09:32:43.6589509Z INFO: Total time: 49.517s
2022-07-08T09:32:43.7462021Z ERROR: Error during SonarScanner execution
2022-07-08T09:32:43.7462346Z INFO: Final Memory: 33M/114M
2022-07-08T09:32:43.7462954Z INFO: ------------------------------------------------------------------------
2022-07-08T09:32:43.7466090Z java.lang.IllegalStateException: No files nor directories matching 'build/classes'
2022-07-08T09:32:43.7473467Z 	at org.sonar.java.classpath.AbstractClasspath.getFilesFromProperty(AbstractClasspath.java:128)
2022-07-08T09:32:43.7477141Z 	at org.sonar.java.classpath.ClasspathForMain.init(ClasspathForMain.java:58)
2022-07-08T09:32:43.7480737Z 	at org.sonar.java.classpath.AbstractClasspath.getElements(AbstractClasspath.java:319)
2022-07-08T09:32:43.7484036Z 	at org.sonar.java.SonarComponents.getJavaClasspath(SonarComponents.java:203)
2022-07-08T09:32:43.7487659Z 	at org.sonar.java.JavaFrontend.<init>(JavaFrontend.java:93)
```

Regarding the version of the plugin, I suppose that there's someone in your organization managing the SonarQube server, that person should be able to tell you what version of the plugin you are currently running and they should also be able to upgrade to 4.2.0 (from Administration / Marketplace). The scanner runs the version of the plugin installed on the server, so you need to upgrade on the server.

**Comment by anbha15** [comment]
I understand your point. But the same thing is working when I use JDK 1.8 for both gradle build and sonar scan with sonarqube version 8.9. Sonar scan is failing only if I use JDK 1.11 for sonar scan and JDK 1.8 for build gradle. That's why I am little surprised. See the attached success log where you see all things same as it is in the error log and it worked for sonarqube 8.9 version.
[log_gradle_build_sonar_scan_working.txt](https://github.com/spotbugs/sonar-findbugs/files/9096957/log_gradle_build_sonar_scan_working.txt)

**Comment by gtoison** [comment]
You upgraded a lot of things so it's not easy to isolate the things that really changed. I've got a very vague suspicion that the SonarQube Thymeleaf plugin might be interacting (by updating the list of the classes to analyse) but I cannot test it because it is not part of the SonarQube community edition. If you can maybe try to disable it
But the most important thing is for you to find out what version of the SpotBugs plugin you are running an preferably upgrade to 4.2.0

**Comment by anbha15** [comment]
No we just upgraded sonarqube server from 8.9 to 9.4. Thats it. But sonarqube 9.4 needs JDK 11 for scanning. So I just changed the github action to pass Java version 2 times in 2 seperate jobs. This is the only change. findbugs version we are using 4.1.4 which is integrated with sonar 9.4 server.

**Comment by gtoison** [comment]
What I meant to say is that upgrading SonarQube also upgraded the plugins bundled with it, for instance the Java or Thymeleaf plugins are part of SonarQube so they are upgraded automatically. On the other hand the findbugs plugin is distributed through the marketplace and users might or might upgrade.
I am not able to test the interactions with the Thymeleaf plugin because it is part of the Enterprise version, and I don't have access to it. Anyway it's just a wild guess, maybe that's not the issue here.
Please try upgrading to 4.2.0 the error message should give more information if the problem persists

**Comment by gtoison** [comment]
Good to hear that upgrading solved the issue!
